version: "3"
services:
  server:
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - config:/config
      - ./custom_components/garmin_mapshare:/config/custom_components/garmin_mapshare
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    ports:
      - 8123:8123
volumes:
  config:
